name: Docker Image Release CI

on:
  push:
    tags:
      - '*'

env:
  APP_NAME: qexo
  DOCKERHUB_REPO: abudulin/qexo

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      app_version: ${{ steps.set_version.outputs.app_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate App Version
        id: set_version
        run: echo "::set-output name=app_version::$(git describe --tags --always)"

  build:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64, linux/386, linux/arm/v6, linux/arm/v7, linux/ppc64le, linux/s390x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Update QEMU
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes -c yes
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          build-args: |
            APP_NAME=${{ env.APP_NAME }}
            APP_VERSION=${{ needs.setup.outputs.app_version }}
          tags: |
            ${{ env.DOCKERHUB_REPO }}:latest
            ${{ env.DOCKERHUB_REPO }}:${{ needs.setup.outputs.app_version }}